version = 1

exclude_patterns = [
  "src/migrations/**",
  "docs/**",
  "src/languages/**",
  "src/assets/**"
]

[[analyzers]]
name = "php"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true